services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cs2_smokes
      POSTGRES_USER: test
      POSTGRES_PASSWORD: tester
    restart: always
    shm_size: 256mb
    ports: 
      - 5432:5432

  adminer:
    image: adminer:latest
    restart: always
    ports: 
      - 11300:8080
