name: Backend CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
      
jobs:
  build: 
    runs-on: self-hosted
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # - name: Copy JAR to mini pc
      #   run: scp target/cs2-smokes-0.0.1-SNAPSHOT.jar ${{ secrets.MINI_PC_HOST }}:~/projects/cs2-smokes

      - name: Build image
        run: docker build -t ${{ secrets.MINI_PC_IP }}:5000/cs2-smokes .

      - name: Push image
        run: docker push ${{ secrets.MINI_PC_IP }}:5000/cs2-smokes
  deploy:
    runs-on: self-hosted
    needs: build
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Deploy
        shell: bash
        run: |
          docker pull ${{ secrets.MINI_PC_IP }}:5000/cs2-smokes
          docker stop cs2-smokes || true
          docker rm cs2-smokes || true
          docker run -d --network cs2-smokes_default --name cs2-smokes --env-file ~/projects/cs2-smokes/.env -p 18080:18080 ${{ secrets.MINI_PC_IP }}:5000/cs2-smokes
          